name: Centralized Rollback

on:
  workflow_call:

jobs:
  centralized_rollback:
    runs-on: ubuntu-latest

    steps:
      - name: Start Rollback
        run: echo "Centralized Rollback Workflow Executed Successfully!"